global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "blogsiteapplication_mc1"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]
  - job_name: "blogsiteapplication_mc2"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8082"]
  - job_name: "blogsiteapplication_mc3"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8083"]
  - job_name: "blogsiteapplication_mc4"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8084"]