name: App Gateway CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'app-gateway/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -f app-gateway/pom.xml clean install