name: Angular CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: ng build --prod

    - name: Run Tests and Generate Code Coverage
      run: ng test --watch=false --browsers=ChromeHeadless --code-coverage

    - name: Print Code Coverage Summary
      run: cat ./coverage/lcov.info | npx coveralls