name: User Service CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'user-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -f user-service/pom.xml clean install

    - name: List contents of user-service directory
      run: ls -l user-service

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: user-service
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/userservice:latest