name: User Service CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'user-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -f user-service/pom.xml clean install

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      env:
        DOCKER_HUB_USERNAME: ${{ secrets[format('{0}_DOCKER_HUB_USERNAME', steps.vars.outputs.env)] }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets[format('{0}_DOCKER_HUB_ACCESS_TOKEN', steps.vars.outputs.env)] }}
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_HUB_USERNAME }}/your-image-name:latest